name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push backend image
      uses: docker/build-push-action@v3
      with:
        context: node-backend
        file: node-backend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/node-backend:latest

    - name: Build and push frontend image
      uses: docker/build-push-action@v3
      with:
        context: react-frontend
        file: react-frontend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/react-frontend:latest